import type { CannedResponse, Ticket, TicketActivity, User } from './types';
import { computeSlaDeadline } from './utils/slaCalculator';

export const MOCK_USERS: User[] = [
  {
    id: 'usr_student_1',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@college.edu',
    role: 'STUDENT',
    usn: '1MS22CS084',
    phone: '+91 98450 12345',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=120&q=80',
  },
  {
    id: 'usr_staff_accounts',
    name: 'Priya Nair',
    email: 'priya.nair@college.edu',
    role: 'STAFF',
    department: 'ACCOUNTS',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=120&q=80',
  },
  {
    id: 'usr_staff_registrar',
    name: 'Dr. Suresh Babu',
    email: 'suresh.babu@college.edu',
    role: 'STAFF',
    department: 'ACADEMIC_REGISTRAR',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=120&q=80',
  },
  {
    id: 'usr_staff_exam',
    name: 'Anita Desai',
    email: 'anita.desai@college.edu',
    role: 'STAFF',
    department: 'EXAMINATION_CELL',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=120&q=80',
  },
  {
    id: 'usr_admin_dean',
    name: 'Prof. K. R. Raman',
    email: 'dean.affairs@college.edu',
    role: 'ADMIN',
    department: 'STUDENT_AFFAIRS',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=120&q=80',
  },
];

export const CANNED_RESPONSES: CannedResponse[] = [
  {
    id: 'cr_1',
    title: 'Bank UTR Verification Pending',
    category: 'FEES_AND_PAYMENTS',
    text: 'We have received your payment query. The finance office is reconciling your transaction with the college bank statement. This normally takes 24–48 banking hours. Please keep your UPI/NetBanking transaction slip handy.',
  },
  {
    id: 'cr_2',
    title: 'Duplicate ID Card Documents Needed',
    category: 'ID_CARD_AND_ACCESS',
    text: 'Please submit a copy of the General Diary (GD) entry / Lost Report from the local police station along with the fee receipt of ₹250 paid at the accounts counter.',
  },
  {
    id: 'cr_3',
    title: 'Bonafide Certificate Ready for Pickup',
    category: 'CERTIFICATES_AND_DOCS',
    text: 'Your Bonafide Certificate has been approved, stamped, and signed by the Registrar. You may collect the physical copy from Counter 2 between 10:00 AM and 1:00 PM on any working day.',
  },
  {
    id: 'cr_4',
    title: 'Attendance Medical Exemption Criteria',
    category: 'ATTENDANCE_AND_LEAVE',
    text: 'Medical certificates must be endorsed by the Campus Medical Officer within 7 days of resuming classes. Please attach the hospital discharge summary and prescription receipts.',
  },
  {
    id: 'cr_5',
    title: 'Hall Ticket Clearance Process',
    category: 'EXAM_AND_HALL_TICKET',
    text: 'Hall ticket withholds due to attendance or fee dues require clearance chalan from both the Accounts Department and Department HOD before final release.',
  },
];

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 60 * 60 * 1000).toISOString();
const daysAgo = (d: number) => new Date(now.getTime() - d * 24 * 60 * 60 * 1000).toISOString();

export const INITIAL_TICKETS: Ticket[] = [
  {
    id: 'tkt_1042',
    ticketNumber: 'TKT-2026-1042',
    title: 'Fee installment receipt not reflecting in ERP portal after UPI transaction',
    description: 'I paid Semester 6 tuition installment fee of ₹45,000 on 23rd Sept via UPI. Amount was debited from SBI account (Ref: UPI/2026/8947231/CR), but ERP still displays "Payment Pending" and late fee warning.',
    category: 'FEES_AND_PAYMENTS',
    subcategory: 'Online Payment Discrepancy',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    department: 'ACCOUNTS',
    studentId: 'usr_student_1',
    studentName: 'Rahul Sharma',
    studentUsn: '1MS22CS084',
    studentEmail: 'rahul.sharma@college.edu',
    studentPhone: '+91 98450 12345',
    studentDepartment: 'Computer Science & Engineering',
    studentSemester: 6,
    assignedToId: 'usr_staff_accounts',
    assignedToName: 'Priya Nair',
    assignedToRole: 'Accounts Officer',
    createdAt: hoursAgo(30),
    updatedAt: hoursAgo(2),
    firstResponseAt: hoursAgo(24),
    slaResponseHours: 8,
    slaResolutionHours: 36,
    slaDeadline: computeSlaDeadline(hoursAgo(30), 'HIGH'),
    slaStatus: 'WARNING', // Near 36h limit
    totalPausedMinutes: 0,
    escalationLevel: 'NONE',
    attachments: [
      { name: 'UPI_Transaction_Debited_Proof.pdf', size: '342 KB', type: 'application/pdf' },
    ],
    tags: ['UPI', 'Tuition-Fee', 'Urgent-Ledger'],
  },
  {
    id: 'tkt_1039',
    ticketNumber: 'TKT-2026-1039',
    title: 'URGENT: Hall ticket withheld due to sports attendance exemption not updated',
    description: 'I represented the college at the All-India Inter-University Badminton Tournament from Sept 10–18. The sports quota attendance OD has not been synced with Exam Cell. My semester exam starts Monday and hall ticket is locked!',
    category: 'EXAM_AND_HALL_TICKET',
    subcategory: 'Hall Ticket Block',
    priority: 'CRITICAL',
    status: 'OPEN',
    department: 'EXAMINATION_CELL',
    studentId: 'usr_student_ananya',
    studentName: 'Ananya Iyer',
    studentUsn: '1MS22EC014',
    studentEmail: 'ananya.iyer@college.edu',
    studentPhone: '+91 99880 54321',
    studentDepartment: 'Electronics & Communication',
    studentSemester: 6,
    assignedToId: 'usr_staff_exam',
    assignedToName: 'Anita Desai',
    assignedToRole: 'Examination Cell Officer',
    createdAt: hoursAgo(26), // 26h ago, Critical SLA is 18h -> BREACHED!
    updatedAt: hoursAgo(26),
    slaResponseHours: 4,
    slaResolutionHours: 18,
    slaDeadline: computeSlaDeadline(hoursAgo(26), 'CRITICAL'),
    slaStatus: 'BREACHED',
    totalPausedMinutes: 0,
    escalationLevel: 'LEVEL_2_EXECUTIVE',
    escalationReason: 'Critical SLA breached by 8 hours during active exam hall ticket distribution window.',
    escalatedAt: hoursAgo(8),
    attachments: [
      { name: 'Sports_Directorate_OD_Letter.pdf', size: '1.2 MB', type: 'application/pdf' },
    ],
    tags: ['Sports-OD', 'Hall-Ticket', 'Escalated-L2'],
  },
  {
    id: 'tkt_1035',
    ticketNumber: 'TKT-2026-1035',
    title: 'Lost Smart ID Card on Campus Shuttle Bus - Duplicate card request',
    description: 'Misplaced my college smart identity card while travelling on Route 4 campus shuttle on 20th September. Security is currently stopping me at the main academic block turnstile.',
    category: 'ID_CARD_AND_ACCESS',
    subcategory: 'Replacement ID Card',
    priority: 'MEDIUM',
    status: 'PENDING_STUDENT_ACTION', // Paused!
    department: 'STUDENT_AFFAIRS',
    studentId: 'usr_student_karthik',
    studentName: 'Karthik Rao',
    studentUsn: '1MS23ME045',
    studentEmail: 'karthik.rao@college.edu',
    studentPhone: '+91 97401 22334',
    studentDepartment: 'Mechanical Engineering',
    studentSemester: 4,
    assignedToId: 'usr_admin_dean',
    assignedToName: 'Prof. K. R. Raman',
    assignedToRole: 'Dean of Student Affairs',
    createdAt: daysAgo(2),
    updatedAt: hoursAgo(10),
    firstResponseAt: hoursAgo(14),
    slaResponseHours: 24,
    slaResolutionHours: 72,
    slaDeadline: computeSlaDeadline(daysAgo(2), 'MEDIUM'),
    slaStatus: 'PAUSED',
    slaPausedAt: hoursAgo(10),
    totalPausedMinutes: 600, // 10 hours paused
    escalationLevel: 'NONE',
    attachments: [],
    tags: ['ID-Card', 'Campus-Access', 'Awaiting-Police-GD'],
  },
  {
    id: 'tkt_1028',
    ticketNumber: 'TKT-2026-1028',
    title: 'Request for Bonafide Certificate for National Scholarship Portal (NSP)',
    description: 'Need an official stamped bonafide certificate stating current enrollment and estimated annual fee structure for submitting NSP Central Sector Scholarship renewal.',
    category: 'CERTIFICATES_AND_DOCS',
    subcategory: 'Bonafide Certificate',
    priority: 'LOW',
    status: 'RESOLVED',
    department: 'ACADEMIC_REGISTRAR',
    studentId: 'usr_student_1',
    studentName: 'Rahul Sharma',
    studentUsn: '1MS22CS084',
    studentEmail: 'rahul.sharma@college.edu',
    studentPhone: '+91 98450 12345',
    studentDepartment: 'Computer Science & Engineering',
    studentSemester: 6,
    assignedToId: 'usr_staff_registrar',
    assignedToName: 'Dr. Suresh Babu',
    assignedToRole: 'Registrar Office Superintendent',
    createdAt: daysAgo(3),
    updatedAt: hoursAgo(5),
    firstResponseAt: daysAgo(2),
    resolvedAt: hoursAgo(5),
    slaResponseHours: 48,
    slaResolutionHours: 120,
    slaDeadline: computeSlaDeadline(daysAgo(3), 'LOW'),
    slaStatus: 'ON_TRACK',
    totalPausedMinutes: 0,
    escalationLevel: 'NONE',
    resolutionSummary: 'Verified active enrollment records. Signed bonafide certificate issued with Dispatch No: REG/2026/BF-891. Stamped copy ready at Counter 2.',
    rootCauseCategory: 'Standard Administrative Request',
    feedbackRating: 5,
    feedbackComment: 'Prompt and clear communication. Picked up the document today without delay!',
    attachments: [
      { name: 'NSP_Application_Draft.pdf', size: '512 KB', type: 'application/pdf' },
    ],
    tags: ['Scholarship', 'NSP', 'Bonafide'],
  },
  {
    id: 'tkt_1048',
    ticketNumber: 'TKT-2026-1048',
    title: 'Hostel Block B Room 304 - AC water leakage and power trip',
    description: 'The split AC unit in Room 304 is leaking heavily onto the study table and causing the MCB to trip repeatedly when turned on. Need immediate electrician inspection.',
    category: 'HOSTEL_AND_CAMPUS',
    subcategory: 'Maintenance & Repairs',
    priority: 'HIGH',
    status: 'OPEN',
    department: 'HOSTEL_ADMIN',
    studentId: 'usr_student_vikram',
    studentName: 'Vikram Seth',
    studentUsn: '1MS21IS092',
    studentEmail: 'vikram.seth@college.edu',
    studentPhone: '+91 98112 33445',
    studentDepartment: 'Information Science',
    studentSemester: 8,
    createdAt: hoursAgo(6),
    updatedAt: hoursAgo(6),
    slaResponseHours: 8,
    slaResolutionHours: 36,
    slaDeadline: computeSlaDeadline(hoursAgo(6), 'HIGH'),
    slaStatus: 'ON_TRACK',
    totalPausedMinutes: 0,
    escalationLevel: 'NONE',
    attachments: [],
    tags: ['Hostel', 'Electrical', 'Maintenance'],
  },
  {
    id: 'tkt_1051',
    ticketNumber: 'TKT-2026-1051',
    title: 'Discrepancy in Continuous Internal Assessment (CIE-2) Data Science Marks',
    description: 'My CIE-2 paper for Machine Learning (22CS602) was evaluated out of 50 and scored 46, but ERP displays 26/50. Subject faculty Prof. Vandana confirmed it was a data entry clerical error.',
    category: 'ATTENDANCE_AND_LEAVE',
    subcategory: 'Internal Marks Discrepancy',
    priority: 'MEDIUM',
    status: 'IN_PROGRESS',
    department: 'ACADEMIC_REGISTRAR',
    studentId: 'usr_student_1',
    studentName: 'Rahul Sharma',
    studentUsn: '1MS22CS084',
    studentEmail: 'rahul.sharma@college.edu',
    studentPhone: '+91 98450 12345',
    studentDepartment: 'Computer Science & Engineering',
    studentSemester: 6,
    assignedToId: 'usr_staff_registrar',
    assignedToName: 'Dr. Suresh Babu',
    assignedToRole: 'Registrar Office Superintendent',
    createdAt: hoursAgo(18),
    updatedAt: hoursAgo(4),
    firstResponseAt: hoursAgo(12),
    slaResponseHours: 24,
    slaResolutionHours: 72,
    slaDeadline: computeSlaDeadline(hoursAgo(18), 'MEDIUM'),
    slaStatus: 'ON_TRACK',
    totalPausedMinutes: 0,
    escalationLevel: 'NONE',
    attachments: [
      { name: 'CIE_Evaluated_Answer_Script.pdf', size: '2.4 MB', type: 'application/pdf' },
    ],
    tags: ['CIE', 'Marks-Correction', 'Faculty-Endorsed'],
  },
  {
    id: 'tkt_1033',
    ticketNumber: 'TKT-2026-1033',
    title: 'Medical Leave attendance condonation for Dengue hospitalization (12 days)',
    description: 'Hospitalized at Apollo Hospital for Dengue fever from Sept 2 to Sept 14. Requesting attendance waiver for 18 theory periods and 4 lab practicals as per university regulation.',
    category: 'ATTENDANCE_AND_LEAVE',
    subcategory: 'Medical Condonation',
    priority: 'HIGH',
    status: 'REOPENED',
    department: 'STUDENT_AFFAIRS',
    studentId: 'usr_student_sneha',
    studentName: 'Sneha Patel',
    studentUsn: '1MS22EE061',
    studentEmail: 'sneha.patel@college.edu',
    studentPhone: '+91 94481 99887',
    studentDepartment: 'Electrical & Electronics',
    studentSemester: 6,
    assignedToId: 'usr_admin_dean',
    assignedToName: 'Prof. K. R. Raman',
    assignedToRole: 'Dean of Student Affairs',
    createdAt: daysAgo(4),
    updatedAt: hoursAgo(3),
    firstResponseAt: daysAgo(3),
    slaResponseHours: 8,
    slaResolutionHours: 36,
    slaDeadline: computeSlaDeadline(daysAgo(4), 'HIGH'),
    slaStatus: 'BREACHED',
    totalPausedMinutes: 120,
    escalationLevel: 'LEVEL_1_BREACH',
    escalationReason: 'Ticket reopened by student with attested CMO medical fitness certificate.',
    attachments: [
      { name: 'Apollo_Discharge_Summary_Stamped.pdf', size: '1.8 MB', type: 'application/pdf' },
    ],
    tags: ['Medical-Condonation', 'Reopened', 'Attendance'],
  },
  {
    id: 'tkt_1015',
    ticketNumber: 'TKT-2026-1015',
    title: 'Library overdue fine dispute - Book deposited in return drop-box before due date',
    description: 'Returned "Computer Networks by Tanenbaum" in the automated library return slot on Friday, but system recorded return on Monday and charged ₹150 overdue fee.',
    category: 'GENERAL_ADMIN',
    subcategory: 'Library Fine Reversal',
    priority: 'LOW',
    status: 'CLOSED',
    department: 'LIBRARY',
    studentId: 'usr_student_rohit',
    studentName: 'Rohit Verma',
    studentUsn: '1MS23CV012',
    studentEmail: 'rohit.verma@college.edu',
    studentPhone: '+91 99001 77665',
    studentDepartment: 'Civil Engineering',
    studentSemester: 4,
    assignedToId: 'usr_staff_accounts',
    assignedToName: 'Priya Nair',
    assignedToRole: 'Accounts Officer',
    createdAt: daysAgo(6),
    updatedAt: daysAgo(2),
    resolvedAt: daysAgo(3),
    closedAt: daysAgo(2),
    slaResponseHours: 48,
    slaResolutionHours: 120,
    slaDeadline: computeSlaDeadline(daysAgo(6), 'LOW'),
    slaStatus: 'ON_TRACK',
    totalPausedMinutes: 0,
    escalationLevel: 'NONE',
    resolutionSummary: 'Verified RFID scanner timestamp log in drop-box. Book was dropped Friday 5:45 PM. ₹150 fine waived from student ledger.',
    rootCauseCategory: 'Hardware / RFID Log Sync Lag',
    feedbackRating: 4,
    feedbackComment: 'Resolved quickly once verified. Thanks!',
    attachments: [],
    tags: ['Library', 'Fine-Waiver', 'RFID'],
  },
];

export const INITIAL_ACTIVITIES: Record<string, TicketActivity[]> = {
  tkt_1042: [
    {
      id: 'act_1042_1',
      ticketId: 'tkt_1042',
      timestamp: hoursAgo(30),
      actorId: 'usr_student_1',
      actorName: 'Rahul Sharma',
      actorRole: 'STUDENT',
      type: 'TICKET_CREATED',
      message: 'Created ticket with attachment: UPI_Transaction_Debited_Proof.pdf',
    },
    {
      id: 'act_1042_2',
      ticketId: 'tkt_1042',
      timestamp: hoursAgo(24),
      actorId: 'usr_staff_accounts',
      actorName: 'Priya Nair',
      actorRole: 'STAFF',
      type: 'ASSIGNED',
      message: 'Self-assigned ticket to Priya Nair (Accounts Officer)',
      newValue: 'Priya Nair',
    },
    {
      id: 'act_1042_3',
      ticketId: 'tkt_1042',
      timestamp: hoursAgo(24),
      actorId: 'usr_staff_accounts',
      actorName: 'Priya Nair',
      actorRole: 'STAFF',
      type: 'INTERNAL_NOTE',
      message: 'Internal Note: UTR number submitted matches SBI Merchant PG batch from yesterday. Escalated batch reconciliation with Canara Bank gateway team.',
    },
    {
      id: 'act_1042_4',
      ticketId: 'tkt_1042',
      timestamp: hoursAgo(2),
      actorId: 'usr_staff_accounts',
      actorName: 'Priya Nair',
      actorRole: 'STAFF',
      type: 'PUBLIC_REPLY',
      message: 'Dear Rahul, we have located the uncredited UPI batch from Sept 23. The transaction is being cleared by our bank. Your ERP receipt will be generated automatically by this evening.',
    },
  ],
  tkt_1039: [
    {
      id: 'act_1039_1',
      ticketId: 'tkt_1039',
      timestamp: hoursAgo(26),
      actorId: 'usr_student_ananya',
      actorName: 'Ananya Iyer',
      actorRole: 'STUDENT',
      type: 'TICKET_CREATED',
      message: 'Raised CRITICAL ticket: Hall ticket withheld due to sports attendance exemption.',
    },
    {
      id: 'act_1039_2',
      ticketId: 'tkt_1039',
      timestamp: hoursAgo(8),
      actorId: 'system',
      actorName: 'SLA Engine',
      actorRole: 'SYSTEM',
      type: 'ESCALATED',
      message: 'SLA BREACH ALERT: Ticket exceeded Critical resolution SLA (18 hours). Automatically escalated to Level 2 (Executive Dean Oversight).',
      newValue: 'LEVEL_2_EXECUTIVE',
    },
  ],
  tkt_1035: [
    {
      id: 'act_1035_1',
      ticketId: 'tkt_1035',
      timestamp: daysAgo(2),
      actorId: 'usr_student_karthik',
      actorName: 'Karthik Rao',
      actorRole: 'STUDENT',
      type: 'TICKET_CREATED',
      message: 'Requested duplicate ID card replacement.',
    },
    {
      id: 'act_1035_2',
      ticketId: 'tkt_1035',
      timestamp: hoursAgo(10),
      actorId: 'usr_admin_dean',
      actorName: 'Prof. K. R. Raman',
      actorRole: 'ADMIN',
      type: 'STATUS_CHANGED',
      message: 'Status changed to Pending Student Action. SLA paused. Required: Police Lost Report & ₹250 receipt.',
      previousValue: 'OPEN',
      newValue: 'PENDING_STUDENT_ACTION',
    },
  ],
};
